version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  flow1:
    jobs:
      - job_a
  
jobs:
  job_a:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - run: exit 1
          # name: failing_step
          # shell: /bin/bash
          # command: return 1
      - run:
          name: On failure
          command: echo "Made to fail"
          when: on_fail
