version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yaml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  configure_infrastructure:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["ba:0b:b0:54:65:e2:80:dc:37:33:75:5f:f4:f4:65:ed"]
        - run:
          name: Install Ansible
          command: |
                apk add --update ansible
        - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i xxxxxx  main.yml 
  smoke_test_job:
      docker: 
        - image: alpine:latest
      steps: 
        - run: apk add --update curl
        - run:
            name: smoke test
            command: |
              URL="https://google.com"
              if curl -s --head $URL
              then
                echo "it worked"
                return 0
              else
                echo "IT failed"
                return 1
              fi

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infrastructure
      - smoke_test_job 
      # configure_infrastructure
